services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    environment:
      - CORS_ALLOWED_ORIGIN=http://localhost:${FRONTEND_PORT:-3000}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
      - BOT_SEARCH_DEPTH=${BOT_SEARCH_DEPTH:-4}

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8080}
    depends_on:
      - backend
