name: Scala CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
      
    - name: Cache sbt dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
          
    - name: Compile backend
      run: sbt backend/compile
      
    - name: Compile frontend
      run: sbt frontend/fastLinkJS
      
    - name: Run tests
      run: sbt test
      
    - name: Check code formatting
      run: sbt scalafmtCheck || echo "Code formatting check skipped (scalafmt not configured)"
